apiVersion: v1
kind: Service
metadata:
  name: custom-404-backend
  namespace: ingress-nginx
spec:
  selector:
    app: custom-404
  ports:
  - port: 80
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: custom-404-backend
  namespace: ingress-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: custom-404
  template:
    metadata:
      labels:
        app: custom-404
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: config
          mountPath: /etc/nginx/conf.d
      volumes:
      - name: config
        configMap:
          name: nginx-404-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-404-config
  namespace: ingress-nginx
data:
  default.conf: |
    server {
        listen 8080;
        location / {
            return 301 https://google.com;
        }
    }
