apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki-stack
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: loki-stack
      version: 2.10.2
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  values:
    loki:
      enabled: true
      auth_enabled: false
      commonConfig:
        replication_factor: 1
      storage:
        type: filesystem
    promtail:
      enabled: true
      config:
        clients:
        - url: http://loki:3100/loki/api/v1/push
    grafana:
      enabled: false
