apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 5m
  timeout: 15m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 55.5.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  values:
    defaultRules:
      create: false
    alertmanager:
      enabled: false
    prometheus:
      enabled: true
      prometheusSpec:
        retention: 2d
        resources:
          requests:
            memory: 400Mi
            cpu: 100m
    grafana:
      enabled: true
      adminPassword: admin123
      ingress:
        enabled: true
        ingressClassName: nginx
        hosts:
        - app-monitor.local
