apiVersion: v1
kind: Secret
metadata:
    name: mysql-secret
    namespace: wordpress
type: Opaque
stringData:
    mysql-root-password: mywordpresspass123
    mysql-user: wordpress
    mysql-password: mywordpresspass123
    mysql-database: wordpress
