apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mysql
  namespace: wordpress
spec:
  interval: 5m
  chart:
    spec:
      chart: mysql
      version: 9.17.1
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    auth:
      existingSecret: mysql-secret
      database: wordpress
      username: wpuser
